package org.gillius.jalleg.binding;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ALLEGRO_HAPTIC_CONDITION_EFFECT extends Structure {
	public double right_saturation;
	public double left_saturation;
	public double right_coeff;
	public double left_coeff;
	public double deadband;
	public double center;
	public ALLEGRO_HAPTIC_CONDITION_EFFECT() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("right_saturation", "left_saturation", "right_coeff", "left_coeff", "deadband", "center");
	}
	public ALLEGRO_HAPTIC_CONDITION_EFFECT(double right_saturation, double left_saturation, double right_coeff, double left_coeff, double deadband, double center) {
		super();
		this.right_saturation = right_saturation;
		this.left_saturation = left_saturation;
		this.right_coeff = right_coeff;
		this.left_coeff = left_coeff;
		this.deadband = deadband;
		this.center = center;
	}
	public ALLEGRO_HAPTIC_CONDITION_EFFECT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ALLEGRO_HAPTIC_CONDITION_EFFECT implements Structure.ByReference {
		
	};
	public static class ByValue extends ALLEGRO_HAPTIC_CONDITION_EFFECT implements Structure.ByValue {
		
	};
}
