package org.gillius.jalleg.binding;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ALLEGRO_VERTEX_ELEMENT extends Structure {
	public int attribute;
	public int storage;
	public int offset;
	public ALLEGRO_VERTEX_ELEMENT() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("attribute", "storage", "offset");
	}
	public ALLEGRO_VERTEX_ELEMENT(int attribute, int storage, int offset) {
		super();
		this.attribute = attribute;
		this.storage = storage;
		this.offset = offset;
	}
	public ALLEGRO_VERTEX_ELEMENT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ALLEGRO_VERTEX_ELEMENT implements Structure.ByReference {
		
	};
	public static class ByValue extends ALLEGRO_VERTEX_ELEMENT implements Structure.ByValue {
		
	};
}
