/*
 * Copyright 2016 Jason Winnebeck
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.gillius.jalleg.binding;
import com.sun.jna.Pointer;
import com.sun.jna.Union;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ALLEGRO_EVENT extends Union {
	public int type;
	public ALLEGRO_ANY_EVENT any;
	public ALLEGRO_DISPLAY_EVENT display;
	public ALLEGRO_JOYSTICK_EVENT joystick;
	public ALLEGRO_KEYBOARD_EVENT keyboard;
	public ALLEGRO_MOUSE_EVENT mouse;
	public ALLEGRO_TIMER_EVENT timer;
	public ALLEGRO_TOUCH_EVENT touch;
	public ALLEGRO_USER_EVENT user;
	public ALLEGRO_EVENT() {
		super();
	}
	public ALLEGRO_EVENT(int type) {
		super();
		this.type = type;
		setType(Integer.TYPE);
	}
	public ALLEGRO_EVENT(ALLEGRO_ANY_EVENT any) {
		super();
		this.any = any;
		setType(ALLEGRO_ANY_EVENT.class);
	}
	public ALLEGRO_EVENT(ALLEGRO_DISPLAY_EVENT display) {
		super();
		this.display = display;
		setType(ALLEGRO_DISPLAY_EVENT.class);
	}
	public ALLEGRO_EVENT(ALLEGRO_JOYSTICK_EVENT joystick) {
		super();
		this.joystick = joystick;
		setType(ALLEGRO_JOYSTICK_EVENT.class);
	}
	public ALLEGRO_EVENT(ALLEGRO_KEYBOARD_EVENT keyboard) {
		super();
		this.keyboard = keyboard;
		setType(ALLEGRO_KEYBOARD_EVENT.class);
	}
	public ALLEGRO_EVENT(ALLEGRO_MOUSE_EVENT mouse) {
		super();
		this.mouse = mouse;
		setType(ALLEGRO_MOUSE_EVENT.class);
	}
	public ALLEGRO_EVENT(ALLEGRO_TIMER_EVENT timer) {
		super();
		this.timer = timer;
		setType(ALLEGRO_TIMER_EVENT.class);
	}
	public ALLEGRO_EVENT(ALLEGRO_TOUCH_EVENT touch) {
		super();
		this.touch = touch;
		setType(ALLEGRO_TOUCH_EVENT.class);
	}
	public ALLEGRO_EVENT(ALLEGRO_USER_EVENT user) {
		super();
		this.user = user;
		setType(ALLEGRO_USER_EVENT.class);
	}
	public ALLEGRO_EVENT(Pointer peer) {
		super(peer);
	}

	@SuppressWarnings("unchecked")
	public <T> T asType(Class<T> type) {
		return (T) getTypedValue(type);
	}

	public static class ByReference extends ALLEGRO_EVENT implements com.sun.jna.Structure.ByReference {
		
	};
	public static class ByValue extends ALLEGRO_EVENT implements com.sun.jna.Structure.ByValue {
		
	};
}
