package org.gillius.jalleg.binding;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ALLEGRO_FONT_VTABLE extends Structure {
	public ALLEGRO_FONT_VTABLE.font_height_callback font_height;
	public ALLEGRO_FONT_VTABLE.font_ascent_callback font_ascent;
	public ALLEGRO_FONT_VTABLE.font_descent_callback font_descent;
	public ALLEGRO_FONT_VTABLE.char_length_callback char_length;
	public ALLEGRO_FONT_VTABLE.text_length_callback text_length;
	public ALLEGRO_FONT_VTABLE.render_char_callback render_char;
	public ALLEGRO_FONT_VTABLE.render_callback render;
	public ALLEGRO_FONT_VTABLE.destroy_callback destroy;
	public ALLEGRO_FONT_VTABLE.get_text_dimensions_callback get_text_dimensions;
	public ALLEGRO_FONT_VTABLE.get_font_ranges_callback get_font_ranges;
	public ALLEGRO_FONT_VTABLE.get_glyph_dimensions_callback get_glyph_dimensions;
	public ALLEGRO_FONT_VTABLE.get_glyph_advance_callback get_glyph_advance;
	public interface font_height_callback extends Callback {
		int apply(ALLEGRO_FONT f);
	};
	public interface font_ascent_callback extends Callback {
		int apply(ALLEGRO_FONT f);
	};
	public interface font_descent_callback extends Callback {
		int apply(ALLEGRO_FONT f);
	};
	public interface char_length_callback extends Callback {
		int apply(ALLEGRO_FONT f, int ch);
	};
	public interface text_length_callback extends Callback {
		int apply(ALLEGRO_FONT f, ALLEGRO_USTR text);
	};
	public interface render_char_callback extends Callback {
		int apply(ALLEGRO_FONT f, org.gillius.jalleg.binding.ALLEGRO_COLOR.ByValue color, int ch, float x, float y);
	};
	public interface render_callback extends Callback {
		int apply(ALLEGRO_FONT f, org.gillius.jalleg.binding.ALLEGRO_COLOR.ByValue color, ALLEGRO_USTR text, float x, float y);
	};
	public interface destroy_callback extends Callback {
		void apply(ALLEGRO_FONT f);
	};
	public interface get_text_dimensions_callback extends Callback {
		void apply(ALLEGRO_FONT f, ALLEGRO_USTR text, IntByReference bbx, IntByReference bby, IntByReference bbw, IntByReference bbh);
	};
	public interface get_font_ranges_callback extends Callback {
		int apply(ALLEGRO_FONT font, int ranges_count, IntByReference ranges);
	};
	public interface get_glyph_dimensions_callback extends Callback {
		byte apply(ALLEGRO_FONT f, int codepoint, IntByReference bbx, IntByReference bby, IntByReference bbw, IntByReference bbh);
	};
	public interface get_glyph_advance_callback extends Callback {
		int apply(ALLEGRO_FONT font, int codepoint1, int codepoint2);
	};
	public ALLEGRO_FONT_VTABLE() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("font_height", "font_ascent", "font_descent", "char_length", "text_length", "render_char", "render", "destroy", "get_text_dimensions", "get_font_ranges", "get_glyph_dimensions", "get_glyph_advance");
	}
	public ALLEGRO_FONT_VTABLE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ALLEGRO_FONT_VTABLE implements Structure.ByReference {
		
	};
	public static class ByValue extends ALLEGRO_FONT_VTABLE implements Structure.ByValue {
		
	};
}
