package org.gillius.jalleg.binding;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ALLEGRO_FONT extends Structure {
	public Pointer data;
	public int height;
	public ALLEGRO_FONT.ByReference fallback;
	public org.gillius.jalleg.binding.ALLEGRO_FONT_VTABLE.ByReference vtable;
	public ALLEGRO_FONT() {
		super();
		setAutoSynch(false);
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("data", "height", "fallback", "vtable");
	}
	public ALLEGRO_FONT(Pointer peer) {
		super(peer);
		setAutoSynch(false);
	}
	public static class ByReference extends ALLEGRO_FONT implements Structure.ByReference {
		
	};
	public static class ByValue extends ALLEGRO_FONT implements Structure.ByValue {
		
	};
}
