/*
 * Copyright 2016 Jason Winnebeck
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.gillius.jalleg.binding;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import java.util.Arrays;
import java.util.List;
import org.gillius.jalleg.binding.AllegroLibrary.ALLEGRO_USER_EVENT_DESCRIPTOR;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ALLEGRO_USER_EVENT extends Structure {
	public int type;
	public AllegroLibrary.ALLEGRO_EVENT_SOURCE source;
	public double timestamp;
	public ALLEGRO_USER_EVENT_DESCRIPTOR __internal__descr;
	public IntByReference data1;
	public IntByReference data2;
	public IntByReference data3;
	public IntByReference data4;
	public ALLEGRO_USER_EVENT() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("type", "source", "timestamp", "__internal__descr", "data1", "data2", "data3", "data4");
	}
	public ALLEGRO_USER_EVENT(int type, AllegroLibrary.ALLEGRO_EVENT_SOURCE source, double timestamp, ALLEGRO_USER_EVENT_DESCRIPTOR __internal__descr, IntByReference data1, IntByReference data2, IntByReference data3, IntByReference data4) {
		super();
		this.type = type;
		this.source = source;
		this.timestamp = timestamp;
		this.__internal__descr = __internal__descr;
		this.data1 = data1;
		this.data2 = data2;
		this.data3 = data3;
		this.data4 = data4;
	}
	public ALLEGRO_USER_EVENT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ALLEGRO_USER_EVENT implements Structure.ByReference {
		
	};
	public static class ByValue extends ALLEGRO_USER_EVENT implements Structure.ByValue {
		
	};
}
