/*
 * Copyright 2016 Jason Winnebeck
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.gillius.jalleg.binding;

import com.sun.jna.Structure;
import org.gillius.jalleg.binding.AllegroLibrary.ALLEGRO_DISPLAY;

import java.util.Arrays;
import java.util.List;

import static org.gillius.jalleg.binding.AllegroLibrary.ALLEGRO_KEY_MAX;
import static org.gillius.jalleg.binding.AllegroLibrary.al_key_down;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ALLEGRO_KEYBOARD_STATE extends Structure {
	/** public */
	public ALLEGRO_DISPLAY display;
	public int[] __key_down__internal__ = new int[(ALLEGRO_KEY_MAX + 31) / 32];

	/**
	 * The default constructor builds an ALLEGRO_KEYBOARD_STATE with "autoSynch" turned off. This means that you cannot
	 * observe the fields from the Java side (it can only be passed into Allegro methods). This is good for performance,
	 * since normally the fields do not need to be observed.
	 */
	public ALLEGRO_KEYBOARD_STATE() {
		super();
		ensureAllocated();
		setAutoSynch(false);
	}

	public ALLEGRO_DISPLAY getDisplay() {
		return (ALLEGRO_DISPLAY) readField("display");
	}

	public boolean isKeyDown(int keyCode) {
		return al_key_down(this, keyCode);
	}

	protected List<? > getFieldOrder() {
		return Arrays.asList("display", "__key_down__internal__");
	}

	public static class ByReference extends ALLEGRO_KEYBOARD_STATE implements Structure.ByReference { }
	public static class ByValue extends ALLEGRO_KEYBOARD_STATE implements Structure.ByValue { }
}
