/*
 * Copyright 2016 Jason Winnebeck
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.gillius.jalleg.binding;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ALLEGRO_MONITOR_INFO extends Structure {
	public int x1;
	public int y1;
	public int x2;
	public int y2;
	public ALLEGRO_MONITOR_INFO() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("x1", "y1", "x2", "y2");
	}
	public ALLEGRO_MONITOR_INFO(int x1, int y1, int x2, int y2) {
		super();
		this.x1 = x1;
		this.y1 = y1;
		this.x2 = x2;
		this.y2 = y2;
	}
	public ALLEGRO_MONITOR_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ALLEGRO_MONITOR_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends ALLEGRO_MONITOR_INFO implements Structure.ByValue {
		
	};
}
