package org.gillius.jalleg.binding;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ALLEGRO_HAPTIC_RUMBLE_EFFECT extends Structure {
	public double strong_magnitude;
	public double weak_magnitude;
	public ALLEGRO_HAPTIC_RUMBLE_EFFECT() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("strong_magnitude", "weak_magnitude");
	}
	public ALLEGRO_HAPTIC_RUMBLE_EFFECT(double strong_magnitude, double weak_magnitude) {
		super();
		this.strong_magnitude = strong_magnitude;
		this.weak_magnitude = weak_magnitude;
	}
	public ALLEGRO_HAPTIC_RUMBLE_EFFECT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ALLEGRO_HAPTIC_RUMBLE_EFFECT implements Structure.ByReference {
		
	};
	public static class ByValue extends ALLEGRO_HAPTIC_RUMBLE_EFFECT implements Structure.ByValue {
		
	};
}
